#ifndef __XR806_LL_PRCM_H__
#define __XR806_LL_PRCM_H__

#include "xr806.h"

#ifdef __cplusplus
extern "C" {
#endif

/* 
 * bits field definition of PRCM->TLDO_CTRL
 */
#define LL_PRCM_TLDO_VOLT_SHIFT                    25
#define LL_PRCM_TLDO_VOLT_WIDTH                    4

#define LL_PRCM_TLDO_EN_SHIFT                      24
#define LL_PRCM_TLDO_EN_WIDTH                      1
#define LL_PRCM_TLDO_EN                            BIT(LL_PRCM_TLDO_EN_SHIFT)

#define LL_PRCM_TLDO_SMPSVOL_SHIFT                 12
#define LL_PRCM_TLDO_SMPSVOL_WIDTH                 4
typedef enum {
    LL_PRCM_SMPS_1V0 = 0,
    LL_PRCM_SMPS_1V1,
    LL_PRCM_SMPS_1V2,
    LL_PRCM_SMPS_1V3,
    LL_PRCM_SMPS_1V4,
    LL_PRCM_SMPS_1V5,
    LL_PRCM_SMPS_1V6,
    LL_PRCM_SMPS_1V7,
    LL_PRCM_SMPS_1V8,
    LL_PRCM_SMSP_1V9,
    LL_PRCM_SMPS_2V0,
    LL_PRCM_SMPS_2V1,
    LL_PRCM_SMPS_2V2,
    LL_PRCM_SMPS_2V3,
    LL_PRCM_SMPS_2V4,
    LL_PRCM_SMPS_2V5,
}LL_PRCM_SMPSVolt;

#define LL_PRCM_TLDO_SMPSON_WHEN_DLDO_OFF_SHIFT    9
#define LL_PRCM_TLDO_SMPSON_WHEN_DLDO_OFF_WIDTH    1
#define LL_PRCM_TLDO_SMPSON_WHEN_DLDO_OFF          BIT(LL_PRCM_TLDO_SMPSON_WHEN_DLDO_OFF_SHIFT)

#define LL_PRCM_TLDO_SMPSOFF_WHEN_SYS_STB_SHIFT    8
#define LL_PRCM_TLDO_SMPSOFF_WHEN_SYS_STB_WIDTH    1
#define LL_PRCM_TLDO_SMPSOFF_WHEN_SYS_STB          BIT(LL_PRCM_TLDO_SMPSOFF_WHEN_SYS_STB_SHIFT)

#define LL_PRCM_TLDO_SMSP_PWMSEL_EN_SHIFT          7
#define LL_PRCM_TLDO_SMSP_PWMSEL_EN_WIDTH          1
#define LL_PRCM_TLDO_SMSP_PWMSEL_EN                BIT(LL_PRCM_TLDO_SMSP_PWMSEL_EN_SHIFT)

typedef enum {
    LL_PRCM_SMPS_PWM_CLK_RFIPDPLL = 0,
    LL_PRCM_SMPS_PWM_CLK_RFIPDCXO,
    LL_PRCM_SMPS_PWM_CLK_WLANPHYEN,
    LL_PRCM_SMSP_PWM_CLK_APPCPUEN,
    LL_PRCM_SMPS_PWM_CLK_WLANCPUEN,
    LL_PRCM_SMPS_PWM_CLK_BLERFEN,
}LL_PRCM_SMPS_ClkSrc;

#define LL_PRCM_TLDO_SMPS_DET_OVR_SHIFT    2
#define LL_PRCM_TLDO_SMPS_DET_OVR_WIDTH    1
#define LL_PRCM_TLDO_SMPS_DET_OVR          BIT(LL_PRCM_TLDO_SMPS_DET_OVR_SHIFT)

#define LL_PRCM_TLDO_SMPS_DET_SHIFT        0
#define LL_PRCM_TLDO_SMPS_DET_WIDTH        1
#define LL_PRCM_TLDO_SMPS_DET              BIT(LL_PRCM_TLDO_SMPS_DET_SHIFT)

/* 
 * bits field definition of PRCM->LDO_MISC
 */

#define LL_PRCM_LDOM_DLDO_RVOLT_SHIFT      24
#define LL_PRCM_LDOM_DLDO_RVOLT_WIDTH      4
typedef enum{
    LL_PRCM_DLDO_RVOLT_1125MV = 0,
    LL_PRCM_DLDO_RVOLT_1025MV,
    LL_PRCM_DLDO_RVOLT_0925MV,
    LL_PRCM_DLDO_RVOLT_0825MV,
    LL_PRCM_DLDO_RVOLT_0725MV,
    LL_PRCM_DLDO_RVOLT_0625MV,
    LL_PRCM_DLDO_RVOLT_1175MV = 8,
    LL_PRCM_DLDO_RVOLT_1225MV,
    LL_PRCM_DLDO_RVOLT_1275MV,
    LL_PRCM_DLDO_RVOLT_1325MV,
    LL_PRCM_DLDO_RVOLT_1375MV,
}LL_PRCM_DLDORVolt;

#define LL_PRCM_LDOM_ELDO_BYPASS_SHIFT     23
#define LL_PRCM_LDOM_ELDO_BYPASS_WIDTH     1
#define LL_PRCM_LDOM_ELDO_BYPASS           BIT(LL_PRCM_LDOM_ELDO_BYPASS_SHIFT)

#define LL_PRCM_LDOM_ELDO_SWTRIM_SHIFT     21
#define LL_PRCM_LDOM_ELDO_SWTRIM_WIDTH     2

#define LL_PRCM_LDOM_ELDO_SWENA_SHIFT      20
#define LL_PRCM_LDOM_ELDO_SWENA_WIDTH      1
#define LL_PRCM_LDOM_ELDO_SWENA            BIT(LL_PRCM_LDOM_ELDO_SWENA_SHIFT)

#define LL_PRCM_LDOM_ELDO_VOLT_SHIFT       18
#define LL_PRCM_LDOM_ELDO_VOLT_WIDTH       2

typedef enum {
    LL_PRCM_ELDO_VOLT_3V3 = 0,
    LL_PRCM_ELDO_VOLT_3V1,
    LL_PRCM_ELDO_VOLT_2V8,
    LL_PRCM_ELDO_VOLT_2V5,
}PRCM_ELDOVolt;

#define LL_PRCM_LDOM_ELDO_MODE_SHIFT       16
#define LL_PRCM_LDOM_ELDO_MODE_WIDTH       2

typedef enum {
    LL_PRCM_ELDO_MODE_ALWAYS_OFF = 0,  /* Always off */
    LL_PRCM_ELDO_MODE_SAMEAS_TLDO,     /* On/Off same as TOP_LDO */
    LL_PRCM_ELDO_MODE_ALWAYS_ON,       /* Always on */
}LL_PRCM_ELDOMode;

#define LL_PRCM_LDOM_WLAN_SW5_SHIFT        14
#define LL_PRCM_LDOM_WLAN_SW5_WIDTH        1
#define LL_PRCM_LDOM_WLAN_SW5              BIT(LL_PRCM_LDOM_WLAN_SW5_SHIFT)

#define LL_PRCM_LDOM_APP_SW1_SHIFT         8
#define LL_PRCM_LDOM_APP_SW1_WIDTH         1
#define LL_PRCM_LDOM_APP_SW1               BIT(LL_PRCM_LDOM_APP_SW1_SHIFT)

#define LL_PRCM_LDOM_DLDO_VOLT_SHIFT       4
#define LL_PRCM_LDOM_DLDO_VOLT_WIDTH       4
typedef enum {
    LL_PRCM_DLDO_VOLT_1125MV = 0,
    LL_PRCM_DLDO_VOLT_1025MV,
    LL_PRCM_DLDO_VOLT_0925MV,
    LL_PRCM_DLDO_VOLT_0825MV,
    LL_PRCM_DLDO_VOLT_0725MV,
    LL_PRCM_DLDO_VOLT_0625MV,
    LL_PRCM_DLDO_VOLT_1175MV = 8,
    LL_PRCM_DLDO_VOLT_1225MV,
    LL_PRCM_DLDO_VOLT_1275MV,
    LL_PRCM_DLDO_VOLT_1325MV,
    LL_PRCM_DLDO_VOLT_1375MV,
}LL_PRCM_DLDOVolt;

#define LL_PRCM_LDOM_PLDO_EN_SHIFT         1
#define LL_PRCM_LDOM_PLDO_EN_WIDTH         1
#define LL_PRCM_LDOM_PLDO_EN               BIT(LL_PRCM_LDOM_PLDO_EN_SHIFT)

#define LL_PRCM_LDOM_DLDO_EN_SHIFT         0
#define LL_PRCM_LDOM_DLDO_EN_WIDTH         1
#define LL_PRCM_LDOM_DLDO_EN               BIT(LL_PRCM_LDOM_DLDO_EN_SHIFT)

/* 
 * bits field definition of PRCM->LFCLK_CTRL
 */
#define LL_PRCM_LFCLK_OSC32K_EN_SHIFT      31
#define LL_PRCM_LFCLK_OSC32K_EN_WIDTH      1
#define LL_PRCM_LFCLK_OSC32K_EN            BIT(LL_PRCM_LFCLK_OSC32K_EN_SHIFT)

#define LL_PRCM_LFCLK_RC32K_EN_SHIFT       30
#define LL_PRCM_LFCLK_RC32K_EN_WIDTH       1
#define LL_PRCM_LFCLK_RC32K_EN             BIT(LL_PRCM_LFCLK_RC32K_EN_SHIFT)

#define LL_PRCM_LFCLK_SRC_SEL_SHIFT        24
#define LL_PRCM_LFCLK_SRC_SEL_WIDTH        1
#define LL_PRCM_LFCLK_SRC_SEL              BIT(LL_PRCM_LFCLK_SRC_SEL_SHIFT)

#define LL_PRCM_LFCLK_PAD_OUTFAC_SHIFT     8
#define LL_PRCM_LFCLK_PAD_OUTFAC_WIDTH     16

#define LL_PRCM_LFCLK_PAD_OUTSRC_SHIFT     1
#define LL_PRCM_LFCLK_PAD_OURSRC_WIDTH     2
typedef enum{
    LL_PRCM_PAD_OUTSRC_LSI = 0,
    LL_PRCM_PAD_OUTSRC_BLE,
    LL_PRCM_PAD_OUTSRC_RCO_CALIB,
    LL_PRCM_PAD_OUTSRC_HFCLK
}LL_PRCM_PADOutSrc;

#define LL_PRCM_LFCLK_OUT_ENA_SHIFT        0
#define LL_PRCM_LFCLK_OUT_ENA_WIDTH        1
#define LL_PRCM_LFCLK_OUT_ENA              BIT(LL_PRCM_LFCLK_OUT_ENA_SHIFT)

/* 
 * bits field definition of PRCM->HSE_CTRL
 */
#define LL_PRCM_HSECTRL_TYPE_SHIFT         0
#define LL_PRCM_HSECTRL_TYPE_WIDTH         2
typedef enum {
    LL_PRCM_HSE_26M = 0,
    LL_PRCM_HSE_40M,
    LL_PRCM_HSE_24M,
    LL_PRCM_HSE_32M
}LL_PRCM_HSEType;

/* 
 * bits field definition of PRCM->LSI_CALIB_CTRL
 */
#define LL_PRCM_LSICAL_FREQ_SHIFT          8
#define LL_PRCM_LSICAL_FREQ_WIDTH          20

#define LL_PRCM_LSICAL_EN_SHIFT            0
#define LL_PRCM_LSICAL_EN_WIDTH            1
#define LL_PRCM_LSICAL_EN                  BIT(LL_PRCM_LSICAL_EN_SHIFT)

/* 
 * bits field definition of PRCM->PLL_CTRL
 */

#define LL_PRCM_PLLCTRL_EN_SHIFT           31
#define LL_PRCM_PLLCTRL_EN_WIDTH           1
#define LL_PRCM_PLLCTRL_EN                 BIT(LL_PRCM_PLLCTRL_EN_SHIFT)

#define LL_PRCM_PLLCTRL_DITHER_DIS_SHIFT    29
#define LL_PRCM_PLLCTRL_DITHER_DIS_WIDTH    2

#define LL_PRCM_PLLCTRL_FRAC_SHIFT          13
#define LL_PRCM_PLLCTRL_FRAC_WIDTH          16

#define LL_PRCM_PLLCTRL_FRAC_CTRL_SHIFT     12
#define LL_PRCM_PLLCTRL_FRAC_CTRL_WIDTH     1
#define LL_PRCM_PLLCTRL_FRAC_CTRL           BIT(LL_PRCM_PLLCTRL_FRAC_CTRL_WIDTH)

#define LL_PRCM_PLLCTRL_NDIV_SHIFT          4
#define LL_PRCM_PLLCTRL_NDIV_WIDTH          8

#define LL_PRCM_PLLCTRL_FRACM_SHIFT         0
#define LL_PRCM_PLLCTRL_FRACM_WIDTH         4

typedef enum{
    LL_PRCM_PLL_PARAM_HSE_24M = 0x60000281,
    LL_PRCM_PLL_PARAM_HSE_26M = 0x1d89d241,
    LL_PRCM_PLL_PARAM_HSE_40M = 0x60000181,
    LL_PRCM_PLL_PARAM_HSE_32M = 0x600001E1,
}LL_PRCM_PLLParamPreDef;

/* 
 * bits field definition of PRCM->SYS_CLK1_CTRL
 */
#define LL_PRCM_SYSCLK1_ROM_2CYCLE_EN_SHIFT 24
#define LL_PRCM_SYSCLK1_ROM_2CYCLE_EN_WIDTH 1

#define LL_PRCM_SYSCLK1_CPUCLK_SRC_SHIFT    16
#define LL_PRCM_SYSCLK1_CPUCLK_SRC_WIDTH    2

typedef enum {
    LL_PRCM_CPUCLK_SRC_HFCLK = 0,
    LL_PRCM_CPUCLK_SRC_LFCLK,
    LL_PRCM_CPUCLK_SRC_SYSCLK1,
}LL_PRCM_CpuClkSrc;

#define LL_PRCM_SYSCLK1_FACTORM_SHIFT       8
#define LL_PRCM_SYSCLK1_FACTORM_WIDTH       3
typedef enum {
    LL_PRCM_SYSCLK_FACTORM_4 = 0,
    LL_PRCM_SYSCLK_FACTORM_5,
    LL_PRCM_SYSCLK_FACTORM_6,
    LL_PRCM_SYSCLK_FACTORM_7,
    LL_PRCM_SYSCLK_FACTORM_9
}LL_PRCM_SysclkFactorM;

#define LL_PRCM_SYSCLK1_FACTORN_SHIFT       0
#define LL_PRCM_SYSCLK1_FACTORN_WIDTH       4

typedef enum {
    LL_PRCM_SYSCLK_FACTORN_1 = 0,
    LL_PRCM_SYSCLK_FACTORN_2,
    LL_PRCM_SYSCLK_FACTORN_3,
    LL_PRCM_SYSCLK_FACTORN_4,
    LL_PRCM_SYSCLK_FACTORN_5,
    LL_PRCM_SYSCLK_FACTORN_6,
    LL_PRCM_SYSCLK_FACTORN_7,
    LL_PRCM_SYSCLK_FACTORN_8,
    LL_PRCM_SYSCLK_FACTORN_9,
    LL_PRCM_SYSCLK_FACTORN_10,
    LL_PRCM_SYSCLK_FACTORN_11,
    LL_PRCM_SYSCLK_FACTORN_12,
    LL_PRCM_SYSCLK_FACTORN_13,
    LL_PRCM_SYSCLK_FACTORN_14,
    LL_PRCM_SYSCLK_FACTORN_15,
    LL_PRCM_SYSCLK_FACTORN_16,
}LL_PRCM_SysclkFactorN;

/* 
 * bits field definition of PRCM->SYS_CLK3_CTRL
 */
#define LL_PRCM_SYSCLK3_EN_SHIFT                31
#define LL_PRCM_SYSCLK3_EN_WIDTH                1
#define LL_PRCM_SYSCLK3_EN                      BIT(LL_PRCM_SYSCLK3_EN_SHIFT)

#define LL_PRCM_SYSCLK3_WLAN_WKUP_BY_HSE_SHIFT  0
#define LL_PRCM_SYSCLK3_WLAN_WKUP_BY_HSE_WIDTH  1
#define LL_PRCM_SYSCLK3_WLAN_WKUP_BY_HSE        BIT(LL_PRCM_SYSCLK3_WLAN_WKUP_BY_HSE_SHIFT)

/* 
 * bits field definition of PRCM->CODEC_CLK_CTRL
 */
#define LL_PRCM_CCLK_AUDADC_CLK_EN_SHIFT        31
#define LL_PRCM_CCLK_AUDADC_CLK_EN_WIDTH        1
#define LL_PRCM_CCLK_AUDADC_CLK_EN              BIT(LL_PRCM_CCLK_AUDADC_CLK_EN_SHIFT)

#define LL_PRCM_CCLK_AUDAMP_CLK_EN_SHIFT        23
#define LL_PRCM_CCLK_AUDAMP_CLK_EN_WIDTH        1

#define LL_PRCM_CCLK_AUDAMP_FACTORN_SHIFT       16
#define LL_PRCM_CCLK_AUDAMP_FACTORN_WIDTH       5

#define LL_PRCM_CCLK_DEV1_FACTORM_SHIFT         8
#define LL_PRCM_CCLK_DEV1_FACTORM_WIDTH         3
typedef enum {
    LL_PRCM_DEV1_FACTORM_4 = 0,
    LL_PRCM_DEV1_FACTORM_5,
    LL_PRCM_DEV1_FACTORM_6,
    LL_PRCM_DEV1_FACTORM_7,
    LL_PRCM_DEV1_FACTORM_9,
}LL_PRCM_Dev1FactorM;

#define LL_PRCM_CCLK_DEV1_FACTORN_SHIFT         0
#define LL_PRCM_CCLK_DEV1_FACTORN_WIDTH         4

#define LL_PRCM_DCXO_EN_SHIFT                   31
#define LL_PRCM_DCXO_EN_WIDTH                   1
#define LL_PRCM_DCXO_EN                         BIT(LL_PRCM_DCXO_EN_SHIFT)

#define LL_PRCM_DCXO_MODE_SHIFT                 28
#define LL_PRCM_DCXO_MODE_WIDTH                 2
typedef enum {
    LL_PRCM_DCXO_MODE_INTERNAL_CLK = 0,
    LL_PRCM_DCXO_MODE_CRYSTAL,
    LL_PRCM_DCXO_MODE_ANALOG,
    LL_PRCM_DCXO_MODE_DIGITAL,
}LL_PRCM_DCXO_Mode;

#define LL_PRCM_DCXO_FREQ_TRIM_SHIFT            20
#define LL_PRCM_DCXO_FREQ_TRIM_WIDTH            8

#define LL_PRCM_DCXO_ACL_EN_SHIFT               19
#define LL_PRCM_DCXO_ACL_EN_WIDTH               1
#define LL_PRCM_DCXO_ACL_EN                     BIT(LL_PRCM_DCXO_ACL_EN_SHIFT)

#define LL_PRCM_DCXO_BIAS_CURRENT_CTRL_SHIFT    12
#define LL_PRCM_DCXO_BIAS_CURRENT_CTRL_WIDTH    8

#define LL_PRCM_DCXO_RF_DIG_REFCLK_EN_SHIFT     11
#define LL_PRCM_DCXO_RF_DIG_REFCLK_EN_WIDTH     1
#define LL_PRCM_DCXO_RF_DIG_REFCLK_EN           BIT(LL_PRCM_DCXO_RF_DIG_REFCLK_EN_SHIFT)

#define LL_PRCM_DCXO_DPLL_BUF_EN_SHIFT          9
#define LL_PRCM_DCXO_DPLL_BUF_EN_WIDTH          1
#define LL_PRCM_DCXO_DPLL_BUF_EN                BIT(LL_PRCM_DCXO_DPLL_BUF_EN_SHIFT)

#define LL_PRCM_DCXO_DET_SEL_SHIFT              4
#define LL_PRCM_DCXO_DET_SEL_WIDTH              5

#define LL_PRCM_DCXO_DET_AUTO_EN_SHIFT          0
#define LL_PRCM_DCXO_DET_AUTO_EN_WIDTH          1
#define LL_PRCM_DCXO_DET_AUTO_EN                BIT(LL_PRCM_DCXO_DET_AUTO_EN_SHIFT)

/**
 * @brief Enable TOP LDO or disable
 * 
 * @param enable 
 */
__STATIC_FORCEINLINE void LL_PRCM_EnableTOPLDO(PRCM_TypeDef* inst, bool enable) {

}

#ifdef __cplusplus
}
#endif

#endif /* __XR806_LL_PRCM_H__ */
